[package]
name = "ctci04_01_directed_graph_find_path"
version = "0.1.0"
edition = "2024"

[dependencies]
concat-string = "1.0.1"
derive_more = { version = "2.0.1", features = ["display"] }
xml = "0.8.20"
# cargo-watch = "8.5.3"
